
const char* kHprofHeader = 
"Copyright (c) 2003, 2005, Oracle and/or its affiliates. All rights reserved.\n"
"\n"
"Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions\n"
"are met:\n"
"\n"
"  - Redistributions of source code must retain the above copyright\n"
"    notice, this list of conditions and the following disclaimer.\n"
"\n"
"  - Redistributions in binary form must reproduce the above copyright\n"
"    notice, this list of conditions and the following disclaimer in the\n"
"    documentation and/or other materials provided with the distribution.\n"
"\n"
"  - Neither the name of Oracle nor the names of its\n"
"    contributors may be used to endorse or promote products derived\n"
"    from this software without specific prior written permission.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS\n"
"IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,\n"
"THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR\n"
"PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR\n"
"CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\n"
"EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,\n"
"PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\n"
"PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\n"
"LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING\n"
"NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
"SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
"\n"
"\n"
"Header for -agentlib:hprof (or -Xrunhprof) ASCII Output (JDK 5.0 JVMTI based)\n"
"\n"
"WARNING!  This file format is under development, and is subject to\n"
"change without notice.\n"
"\n"
"This file contains the following types of records:\n"
"\n"
"THREAD START\n"
"THREAD END      mark the lifetime of Java threads\n"
"\n"
"TRACE           represents a Java stack trace.  Each trace consists\n"
"                of a series of stack frames.  Other records refer to\n"
"                TRACEs to identify (1) where object allocations have\n"
"                taken place, (2) the frames in which GC roots were\n"
"                found, and (3) frequently executed methods.\n"
"\n"
"HEAP DUMP       is a complete snapshot of all live objects in the Java\n"
"                heap.  Following distinctions are made:\n"
"\n";
